steps:
# Build the application container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_DOCKER_REPO}/${_APP_NAME}:${_VERSION}', '.']
# TEST
- name: 'bash'
  args: ['cp', 'tests', '/persistent_volume/tests']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '--name', '${_APP_NAME}', '--rm', 'gcr.io/${_DOCKER_REPO}/${_APP_NAME}:${_VERSION}', 'env']
- name: 'gcr.io/cloud-builders/docker'
  volumes:
  - name: 'vol1'
    path: '/persistent_volume/tests'
  args: 
  - 'run'
  - '--name'
  - '${_APP_NAME}'
  - '--rm'
  - '-v'
  - 'vol1:/abagdemo'
  - 'gcr.io/${_DOCKER_REPO}/${_APP_NAME}:${_VERSION}'
  - 'ls'
  - '-al /abagdemo'


substitutions:
    # Docker Repo
    _DOCKER_REPO: fckuligowski
    _APP_NAME: abagdemo
    
    # Developers ONLY change
    _VERSION: v1.x
    
options:
    substitution_option: 'ALLOW_LOOSE'