steps:
- id: 'Get Version'
  name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'grep -oP "image:\s+\K(.*)" k8s/abagdemo-deploy.yaml > image_name.txt'

# Build the application container
- id: 'Build the application container'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  args: 
  - '-c'
  - 'docker build -t $(cat image_name.txt) .'