steps:
# Build the application container
- id: 'Build the application container'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_DOCKER_REPO}/${_APP_NAME}:${_VERSION}', '.']

- id: 'Copy tests scripts'
  name: 'bash'
  volumes:
  - name: 'testsvol'
    path: '/persistent_volume/tests'
  args: ['cp', '-R', 'tests', '/persistent_volume']

- id: 'Create Cred Key File'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  volumes:
  - name: 'credsvol'
    path: '/persistent_volume/creds'
  args: ['gcloud', 'iam', 'service-accounts', 'keys', 'create', '--iam-account', '"last-baron-abagdemo@hazel-math-279814.iam.gserviceaccount.com"', '/persistent_volume/creds/service-account.json']


- id: 'Show Env Vars'
  name: 'gcr.io/cloud-builders/docker'
  args: ['run', '--name', '${_APP_NAME}', '--rm', 'gcr.io/${_DOCKER_REPO}/${_APP_NAME}:${_VERSION}', 'env']

- id: 'List Test Scripts'
  name: 'gcr.io/cloud-builders/docker'
  volumes:
  - name: 'testsvol'
    path: '/persistent_volume/tests'
  args: 
  - 'run'
  - '--name'
  - '${_APP_NAME}'
  - '--rm'
  - '-v'
  - 'testsvol:/abagdemo/tests'
  - 'gcr.io/${_DOCKER_REPO}/${_APP_NAME}:${_VERSION}'
  - 'find'
  - '/abagdemo'
  - '-type'
  - 'f'

- id: 'Run Unit Tests'
  name: 'gcr.io/cloud-builders/docker'
  volumes:
  - name: 'testsvol'
    path: '/persistent_volume/tests'
  - name: 'credsvol'
    path: '/persistent_volume/creds'
  args: 
  - 'run'
  - '--name'
  - '${_APP_NAME}'
  - '--rm'
  - '-v'
  - 'testsvol:/abagdemo/tests'
  - '-v'
  - 'credsvol:/abagdemo/creds'
  - 'gcr.io/${_DOCKER_REPO}/${_APP_NAME}:${_VERSION}'
  - '/bin/sh'
  - '-c'
  - '/abagdemo/tests/testit.sh unit'
  env:
  - 'GOOGLE_APPLICATION_CREDENTIALS=/abagdemo/creds/service-account.json'

substitutions:
    # Docker Repo
    _DOCKER_REPO: fckuligowski
    _APP_NAME: abagdemo
    
    # Developers ONLY change
    _VERSION: v1.x
    
options:
    substitution_option: 'ALLOW_LOOSE'