steps:
# Build the application container
- id: 'Build the application container'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_DOCKER_REPO}/${_APP_NAME}:${_VERSION}', '.']

- id: 'Copy test scripts'
  name: 'bash'
  args: ['cp', '-R', 'tests', '/workspace/abagdemo']

- id: 'List Test Scripts'
  name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'run'
  - '--name'
  - '${_APP_NAME}'
  - '--rm'
  - 'gcr.io/${_DOCKER_REPO}/${_APP_NAME}:${_VERSION}'
  - 'find'
  - '/abagdemo'
  - '-type'
  - 'f'

substitutions:
    # Docker Repo
    _DOCKER_REPO: fckuligowski
    _APP_NAME: abagdemo
    # Google Storage Creds
    _GOOGLE_APPLICATION_CREDENTIALS: '/abagdemo/creds/service-account.json'
    
    # Developers ONLY change
    _VERSION: v1.x
    
options:
    substitution_option: 'ALLOW_LOOSE'