steps:
- id: 'Get Version'
  name: 'bash'
  volumes:
  - name: 'vervol'
    path: '/persistent_volume/ver'
  entrypoint: 'sh'
  args:
  - '-c'
  - 'grep -oP "image:\s+\K(.*)" k8s/abagdemo-deploy.yaml > /persistent_volume/ver/image_name.txt'

# Build the application container
- id: 'Build the application container'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: sh
  volumes:
  - name: 'vervol'
    path: '/persistent_volume/ver'
  args: 
  - '-c'
  - 'docker build -t $(cat /persistent_volume/ver/image_name.txt) .'

substitutions:
    # Docker Repo
    _DOCKER_REPO: 'gcr.io/hazel-math-279814'
    _APP_NAME: 'abagdemo-gcp'
    # Google Storage Creds
    _GOOGLE_APPLICATION_CREDENTIALS: '/abagdemo/creds/service-account.json'
    
    # Developers ONLY change
    _VERSION: v1.x
    
options:
    substitution_option: 'ALLOW_LOOSE'