steps:
# Get the Image repo and tag name (version) from the k8s deploy manifest
# image_name.txt = repo + tag name
# image_repo.txt = repo name only
# image_tag.txt = tag name only
- id: 'Get Version'
  name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    grep -oP "image:\s+\K(.*)" ${_K8S_DEPLOY_FILE} > image_name.txt &&
    grep -oP "image:\s+\K(\S+)(?=:)" ${_K8S_DEPLOY_FILE} > image_repo.txt &&
    grep -oP "image:\s+\S+:\K(.*)" ${_K8S_DEPLOY_FILE} > image_tag.txt

# Build the application container
- id: 'Build the application container'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  args: 
  - '-c'
  - 'docker build -t $(cat image_name.txt) .'

# Get the credentials for accessing Google Storage, because the app needs those.
# And for Git because we need those to add a new Tag to the Git repo.
- id: 'Get Creds'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    mkdir -p tmp &&
    gcloud secrets versions access latest --secret=${_GS_CREDS} > tmp/gs_creds.json &&
    gcloud secrets versions access latest --secret=${_GIT_USER} > tmp/git_user.txt &&
    gcloud secrets versions access latest --secret=${_GIT_PWD} > tmp/git_pwd.txt

# Run the application Unit tests
- id: 'Run Unit Tests'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: 
  - '-c'
  - 'docker run --name ${_APP_NAME} --rm -v $(pwd)/tests:/abagdemo/tests -v $(pwd)/tmp:/abagdemo/tmp -e GOOGLE_APPLICATION_CREDENTIALS="/abagdemo/tmp/gs_creds.json" $(cat image_name.txt) /bin/sh -c "/abagdemo/tests/testit.sh unit"'

# Run the application Functional tests
- id: 'Run Functional Tests'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: 
  - '-c'
  - 'docker run --name ${_APP_NAME} --rm -v $(pwd)/tests:/abagdemo/tests -v $(pwd)/tmp:/abagdemo/tmp -e GOOGLE_APPLICATION_CREDENTIALS="/abagdemo/tmp/gs_creds.json" $(cat image_name.txt) /bin/sh -c "/abagdemo/tests/testit.sh functional"'

# Determine if an image has already been created with this tag,
# but only if we're merging into the master branch.
- id: 'Search if Tag Exists'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: 
  - '-c'
  - if test "$BRANCH_NAME" = "master"
    then 
        gcloud container images list-tags $(cat image_repo.txt) --filter="tags=$(cat image_tag.txt)" --format="get(tags)" > image_found.txt
        cat image_found.txt
    else
        echo "Skipping further steps because branch $BRANCH_NAME is not master."
    fi

# Push the image to Google Container Repo, but only if that tag
# doesn't already exist
- id: 'Push Image to Repo'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    if test -f image_found.txt && test "$(cat image_found.txt)" != "$(cat image_tag.txt)"
    then 
        docker push $(cat image_name.txt) || exit 1
    else
        echo "Skipped pushing Container Image to Registry"
    fi

# Add a new Tag to the GitHub repo, but only if that tag
# doesn't already exist
- id: 'Add Tag to Git Repo'
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if test -f image_found.txt && test "$(cat image_found.txt)" != "$(cat image_tag.txt)"
    then
        mkdir tagclone
        cd tagclone
        git clone https://${_GIT_REPO} --config user.name=$(cat ../tmp/git_user.txt) --config user.email="no@nomail.com" || exit 1
        cd ${_APP_NAME}
        git tag -a "$(cat ../../image_tag.txt)" -m "${_GIT_TAG_CMT} $(cat ../../image_tag.txt)" || exit 1
        git push https://$(cat ../../tmp/git_user.txt):$(cat ../../tmp/git_pwd.txt)@${_GIT_REPO} --tags || exit 1
    else
        echo "Skipped creating Tag in Git"
    fi

# Update the container image using kubectl set
- id: 'Update Image in k8s'
  name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if test -f image_found.txt && test "$(cat image_found.txt)" != "$(cat image_tag.txt)"
    then
        gcloud container clusters get-credentials --project=$PROJECT_ID --zone=${_GKE_ZONE} ${_GKE_CLUSTER} || exit 1
        kubectl set image deploy/${_K8S_DEPLOY} ${_K8S_CONT}=$(cat image_name.txt) -n ${_K8S_NS} --record || exit 1
        # kubectl apply -f ${_K8S_DEPLOY_FILE} --record
    else
        echo "Skipped updating Image in k8s"
    fi
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_GKE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

substitutions:
    # Name of our application.
    _APP_NAME: 'abagdemo-gcp'
    # Name of Google Secret that contains the credentials for our app
    # to connect to  Google Storage.
    _GS_CREDS: 'last-baron-abagdemo'
    # Name of the GitHub Repo where our code is.
    _GIT_REPO: github.com/fckuligowski/${_APP_NAME}
    # Name of Google Secrets for GitHub user name and password.
    _GIT_USER: 'fckuligowski-git-user'
    _GIT_PWD: 'fckuligowski-git-pwd'
    # The Git Tag's message field will use this value.
    _GIT_TAG_CMT: 'automatically generated by Google Cloud Build for ${_APP_NAME}'
    # Kubernetes namespace, deployment, and container names.
    _K8S_NS: 'abagdemo'
    _K8S_DEPLOY: '${_K8S_NS}'
    _K8S_CONT: '${_K8S_NS}'
    # Name of the file with the k8s Deployment spec - defines the
    # Container Image Name
    _K8S_DEPLOY_FILE: 'k8s/abagdemo-deploy.yaml'
    # Name of our GKE Kubernetes Cluster
    _GKE_CLUSTER: 'jenkins-cd'
    _GKE_ZONE: 'us-east1-d'

options:
    substitution_option: 'ALLOW_LOOSE'