steps:
- id: 'Get Version'
  name: 'ubuntu'
  volumes:
  - name: 'vervol'
    path: '/persistent_volume/ver'
  entrypoint: 'sh'
  args:
  - '-c'
  - 'grep -oP "image:\s+\K(.*)" k8s/abagdemo-deploy.yaml > /persistent_volume/ver/image_name.txt'

- id: 'Show Version'
  name: 'ubuntu'
  volumes:
  - name: 'vervol'
    path: '/persistent_volume/ver'
  entrypoint: 'sh'
  args:
  - '-c'
  - 'echo XXXX$(cat /persistent_volume/ver/image_name.txt)XXXX'

