steps:
# Build the application container
- id: 'Build the application container'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_DOCKER_REPO}/${_APP_NAME}:${_VERSION}', '.']
# TEST
- id: 'Copy tests scripts'
  name: 'bash'
  volumes:
  - name: 'vol1'
    path: '/persistent_volume'
  args: ['cp', '-R', 'tests', '/persistent_volume']
- id: 'Show Env Vars'
  name: 'gcr.io/cloud-builders/docker'
  args: ['run', '--name', '${_APP_NAME}', '--rm', 'gcr.io/${_DOCKER_REPO}/${_APP_NAME}:${_VERSION}', 'env']
- id: 'List Test Scripts'
  name: 'gcr.io/cloud-builders/docker'
  volumes:
  - name: 'vol1'
    path: '/persistent_volume'
  args: 
  - 'run'
  - '--name'
  - '${_APP_NAME}'
  - '--rm'
  - '-v'
  - 'vol1:/abagdemo'
  - 'gcr.io/${_DOCKER_REPO}/${_APP_NAME}:${_VERSION}'
  - 'find'
  - '/abagdemo/tests'
  - '-type'
  - 'f'
  - '-print'
- id: 'Run Unit Tests'
  name: 'gcr.io/cloud-builders/docker'
  volumes:
  - name: 'vol1'
    path: '/persistent_volume'
  args: 
  - 'run'
  - '--name'
  - '${_APP_NAME}'
  - '--rm'
  - '-v'
  - 'vol1:/abagdemo'
  - 'gcr.io/${_DOCKER_REPO}/${_APP_NAME}:${_VERSION}'
  - 'ls'
  - '-alr'
  - '/abagdemo'

substitutions:
    # Docker Repo
    _DOCKER_REPO: fckuligowski
    _APP_NAME: abagdemo
    
    # Developers ONLY change
    _VERSION: v1.x
    
options:
    substitution_option: 'ALLOW_LOOSE'