steps:
# Get the Image repo and tag name (version) from the k8s deploy manifest
# image_name.txt = repo + tag name
# image_repo.txt = repo name only
# image_tag.txt = tag name only
- id: 'Get Version'
  name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    grep -oP "image:\s+\K(.*)" k8s/abagdemo-deploy.yaml > image_name.txt &&
    grep -oP "image:\s+\K(\S+)(?=:)" k8s/abagdemo-deploy.yaml > image_repo.txt &&
    grep -oP "image:\s+\S+:\K(.*)" k8s/abagdemo-deploy.yaml > image_tag.txt

- id: 'Take a Look'
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cp image_repo.txt image_found.txt && 
    ls -al &&
    pwd 

- id: 'Add Tag to Git Repo'
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if test -f image_found.txt && test "$(cat image_found.txt)" != "$(cat image_tag.txt)"
    then
        mkdir tagclone
        cd tagclone
        git clone 'https://github.com/fckuligowski/abagdemo-gcp'
        cd abagdemo-gcp
        ls -al
        pwd
        git tag -a "$(cat ../../image_tag.txt)" -m "version $(cat ../../image_tag.txt)"
        git push 'https://github.com/fckuligowski/abagdemo-gcp' --tags
        git status
    fi

  #  sh "git tag -a ${imageTag} -m 'abagdemo version ${imageTag}'"
#            sh "git push 'https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/fckuligowski/abagdemo' --tags"

substitutions:
    _APP_NAME: 'abagdemo-gcp'
    _GS_CREDS: 'last-baron-abagdemo'

options:
    substitution_option: 'ALLOW_LOOSE'