steps:
# Get the Image repo and tag name (version) from the k8s deploy manifest
# image_name.txt = repo + tag name
# image_repo.txt = repo name only
# image_tag.txt = tag name only
- id: 'Get Version'
  name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    grep -oP "image:\s+\K(.*)" k8s/abagdemo-deploy.yaml > image_name.txt &&
    grep -oP "image:\s+\K(\S+)(?=:)" k8s/abagdemo-deploy.yaml > image_repo.txt &&
    grep -oP "image:\s+\S+:\K(.*)" k8s/abagdemo-deploy.yaml > image_tag.txt

- id: 'Dummy for image_found.txt'
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cp image_repo.txt image_found.txt && 
    ls -al &&
    pwd 

# Get the credentials for accessing Google Storage, because the app needs those.
# And for Git because we need those to add a new Tag to the Git repo.
- id: 'Get Creds'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    mkdir -p tmp &&
    gcloud secrets versions access latest --secret=${_GS_CREDS} > tmp/gs_creds.json &&
    gcloud secrets versions access latest --secret=${_GIT_USER} > tmp/git_user.txt &&
    gcloud secrets versions access latest --secret=${_GIT_PWD} > tmp/git_pwd.txt

- id: 'Add Tag to Git Repo'
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if test -f image_found.txt && test "$(cat image_found.txt)" != "$(cat image_tag.txt)"
    then
        mkdir tagclone
        cd tagclone
        git clone 'https://github.com/fckuligowski/abagdemo-gcp' --config user.name=$(cat ../../tmp/git_user.txt) || exit 1
        cd abagdemo-gcp
        echo "step 00"
        git tag -a "$(cat ../../image_tag.txt)" -m "version $(cat ../../image_tag.txt)" || exit 1
        echo "step 01"
        git tag
        echo "step 02"
        git push 'https://$(cat ../../tmp/git_user.txt):$(cat ../../tmp/git_pwd.txt)@github.com/fckuligowski/abagdemo-gcp' --tags || exit 1
        echo "step 03"
        git status
        echo "step 04"
    fi


substitutions:
    _APP_NAME: 'abagdemo-gcp'
    _GS_CREDS: 'last-baron-abagdemo'
    _GIT_USER: 'fckuligowski-git-user'
    _GIT_PWD: 'fckuligowski-git-pwd'

options:
    substitution_option: 'ALLOW_LOOSE'