steps:
# Get the Image repo and tag name (version) from the k8s deploy manifest
# image_name.txt = repo + tag name
# image_repo.txt = repo name only
# image_tag.txt = tag name only
- id: 'Get Version'
  name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    grep -oP "image:\s+\K(.*)" k8s/abagdemo-deploy.yaml > image_name.txt &&
    grep -oP "image:\s+\K(\S+)(?=:)" k8s/abagdemo-deploy.yaml > image_repo.txt &&
    grep -oP "image:\s+\S+:\K(.*)" k8s/abagdemo-deploy.yaml > image_tag.txt

- id: 'Take a Look'
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cp image_tag.txt image_found.txt && 
    ls -al &&
    pwd 

- id: 'Git Status'
  name: 'gcr.io/cloud-builders/git'
  dir: /workspace/tagclone
  entrypoint: 'bash'
  args:
  - '-c'
  - |
     if test -f image_found.txt && test "$(cat image_found.txt)" != "$(cat image_tag.txt)"
     then
         git clone 'https://github.com/fckuligowski/abagdemo-gcp'
         cd abagdemo-gcp
         git status
         ls -al
         pwd
     fi

- id: 'Add Tag to Git Repo'
  name: 'gcr.io/cloud-builders/git'
  args: 
  - 'tag'
  - '-a'
  - '$(cat image_tag.txt)'
  - '-m'
  - '"${_APP_NAME} version $(cat image_tag.txt)"'

- id: 'Push Tag to Git Repo'
  name: 'gcr.io/cloud-builders/git'
  args: 
  - 'push'
  - '--tags'

  #  sh "git tag -a ${imageTag} -m 'abagdemo version ${imageTag}'"
#            sh "git push 'https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/fckuligowski/abagdemo' --tags"

substitutions:
    _APP_NAME: 'abagdemo-gcp'
    _GS_CREDS: 'last-baron-abagdemo'

options:
    substitution_option: 'ALLOW_LOOSE'