steps:
- id: 'Create Cred Key'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  volumes:
  - name: 'credsvol'
    path: '/persistent_volume/creds'
  args: 
  - 'gcloud'
  - 'iam'
  - 'service-accounts'
  - 'keys'
  - 'create'
  - '--iam-account'
  - 'last-baron-abagdemo@hazel-math-279814.iam.gserviceaccount.com'
  - '/persistent_volume/creds/service-account.json'

- id: 'Get Key Id'
  name: 'ubuntu'
  volumes:
  - name: 'credsvol'
    path: '/persistent_volume/creds'
  entrypoint: sh
  args:
  - '-c'
  - 'jq ".private_key_id" /persistent_volume/creds/service-account.json -r > /persistent_volume/creds/key.txt'

- id: 'Delete Cred Key'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  volumes:
  - name: 'credsvol'
    path: '/persistent_volume/creds'
  entrypoint: sh
  args: 
  - '-c'
  - 'gcloud iam service-accounts keys delete $(cat /persistent_volume/creds/key.txt) --iam-account "last-baron-abagdemo@hazel-math-279814.iam.gserviceaccount.com" -q'

substitutions:
    # Docker Repo
    _DOCKER_REPO: fckuligowski
    _APP_NAME: abagdemo
    # Google Storage Creds
    _GOOGLE_APPLICATION_CREDENTIALS: '/abagdemo/creds/service-account.json'
    
    # Developers ONLY change
    _VERSION: v1.x
    
options:
    substitution_option: 'ALLOW_LOOSE'