apiVersion: v1
kind: Secret
metadata:
  name: {{ include "abagdemo.fullname" . }}-gcp-creds
  namespace: {{ include "abagdemo.fullname" . }}  
  labels:
    app: {{ include "abagdemo.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  "hazel-math-279814.json": |-
    {{ .Files.Get "creds/hazel-math-279814.json" | b64enc }}