apiVersion: v1
kind: Service
metadata:
  name: abagdemo
  namespace: abagdemo
  labels:
    app: abagdemo
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: abagdemo