# This was part of my Helm Chart, but it would screw up my app
# every time I did 'helm upgrade abagdemo' because it would 
# overwrite this secret (which the app needs). I'm stuck in a
# chicken-and-egg problem.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "abagdemo.fullname" . }}-gcp-creds
  namespace: {{ include "abagdemo.fullname" . }}  
  labels:
    app: {{ include "abagdemo.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  "hazel-math-279814.json": |-
    {{ .Files.Get "creds/hazel-math-279814.json" | b64enc }}